recipeVersion: 1.0.0-alpha.1
applications:
  - name: hackathon-dotnet-app
    containers:
      - name: sample-app 
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/hackathon-2025-dotnet-samples/sample-app:sha-41512af
      - name: database
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/hackathon-2025-dotnet-samples/sample-db:sha-41512af
