recipeVersion: 1.0.0-alpha.1
applications:
  - name: hackathon-dotnet-app
    containers:
      - name: sample-app 
        image: ghcr.io/liciniomendes-vestas/hackathon-2025-dotnet-samples/sample-app:master
      - name: database
        image: ghcr.io/liciniomendes-vestas/hackathon-2025-dotnet-samples/sample-db:master
