applications:
  - name: team-awesome-sample
    containers:
      - name: sample-app 
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/wl-team-awesome/team-awesome:1.0
  - name: team-awesome-ap
    containers:
      - name: ap
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/wl-team-awesome/team-awesome-ap:0.0.5
dependencies:
  - wl-we-want-to-code-more